import { Poppins } from "next/font/google";
import "./globals.css";

// Load Google Font: Poppins
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400"], // kamu bisa tambah ['400', '500', '700'] jika perlu
  variable: "--font-poppins", // optional, berguna kalau pakai CSS variable
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
